### ISSUE TITLE
Zeus Tracker list

### ISSUE THREAD

**Issue by ajp2k13** [nextdns/lists#11]
The Zeus tracker list has been discontinued and should probably be removed from NextDNS?

https://zeustracker.abuse.ch/byebye.php

# ZeuS Tracker has been discontinued on Jul 8th, 2019

**Comment by romaincointepas** [comment]
Added a disclaimer for that list in https://github.com/nextdns/lists/commit/abc661c9a12169e1b7b91230e288f80251fa9f28. we would rather let the users decide if they still want to use it or not.

**Comment by HorayNarea** [comment]
The list is empty, it doesn't make any sense to still include it…

In the worst case the person who operates zeustracker.abuse.ch could start serving a very bad list, in the best case you send requests to their webserver which uses bandwidth/cpu/ram they have to pay for and you/your users don't gain anything from it.

Also it's bad UX to have lists selectable that are not available anymore. Like clicking buttons that don't do anything.
What does your "disclaimer" actually mean?
"Important: this does nothing, or maybe something, or weird things? You decide!" ?

Please just remove lists that are not available anymore.
