### ISSUE TITLE
Support imports/include of external (black|white)lists by URL or Upload-file

### ISSUE THREAD

**Issue by cbuijs** [nextdns/lists#12]
Subject explains it pretty much on its own.

I would like to use the service with my own (extensive) list(s). (see https://github.com/cbuijs/accomplist).

When URL is used, it should pull the list on a definable frequency to get the latest/greatest version.

Or a possibility to post suggested lists to be included (I suggest the plain.* lists of my "standard" repository on above link).

Thanks for consideration!

**Comment by ZeroDot1** [comment]
Yes, this function is very much needed.

**Comment by pe0mot** [comment]
Supported!

**Comment by bdwilson** [comment]
Agreed. I dread entering in the sites by hand to get slickdeals to function.

**Comment by romaincointepas** [comment]
> Or a possibility to post suggested lists to be included (I suggest the plain.* lists of my "standard" repository on above link).

We definitely welcome new list additions by PR on this repo (as long as they make sense to a certain % of our users).

For the rare cases where a user is managing his own private blocklist, we may think about adding support for this in the future, but it's too niche at the moment to be a priority.

> Agreed. I dread entering in the sites by hand to get slickdeals to function.

@bdwilson We will be adding a feature very soon that lets you "not block affiliate/tracking links". I'm assuming that would probably be a better solution?

Side note: highly recommending our subreddit [/r/nextdns](https://www.reddit.com/r/nextdns) for feature requests or UI/UX suggestions as more people can jump in to discuss it.

**Comment by ZeroDot1** [comment]
@romaincointepas Importing a blacklist via URL or upload would be very helpful for blacklist developers to quickly and easily test blacklists to see if a list has problems.
