### ISSUE TITLE
Able to sort and search any list, plus hits

### ISSUE THREAD

**Issue by cbuijs** [nextdns/lists#16]
Would be nice if the lists in the whitelist/blacklist tabs, have a "number-of-hits" next to them.

Also have them sortable (by name and/or hits) and have the same search function as in the logs tab.

**Comment by DaBomby** [comment]
See here for something similar. 

https://github.com/nextdns/lists/issues/34

**Comment by romaincointepas** [comment]
We will greatly improve the Lists and Services sections soon with sorts, filters and more signals (like the risk of false positives of a list).

Closing this, our subreddit [/r/nextdns](https://www.reddit.com/r/nextdns) is probably a better place  to discuss feature requests.
