### ISSUE TITLE
Steam domains incomplete

### ISSUE THREAD

**Issue by zzymurgy** [nextdns/lists#2]
Steam could use a few more domains. I have found these: 
steamstatic.com
steamstore-a.akamaihd.net
steamcdn-a.akamaihd.net
steamusercontent-a.akamaihd.net
steam-chat.com
steamcloud-sydney.storage.googleapis.com
steam.ix.asn.au

**Comment by romaincointepas** [comment]
Added, thanks!

**Comment by SethL** [comment]
a couple more
steamcommunity-a.akamaihd.net.edgesuite.net
steamcommunity-a.akamaihd.net
