### ISSUE TITLE
Analytics & Logs - Filter by device

### ISSUE THREAD

**Issue by vanj** [nextdns/lists#20]
It would be nice to have the ability to filter the Analytics & Logs pages by Device.  

Similarly, Clear Logs for a specific Device

Looks like the current Search function searches the URL, the ability to search (slightly different than filter)  by Device would be nice too.

**Comment by DaBomby** [comment]
I would also be nice if there was a toggle to allow real-time streaming of the logs. Like what you might do with grep on Linux. It would help significantly with troubleshooting.

**Comment by romaincointepas** [comment]
> It would be nice to have the ability to filter the Analytics & Logs pages by Device.

Coming very soon!

> Similarly, Clear Logs for a specific Device

Not sure about that one, it does make sense though.

> I would also be nice if there was a toggle to allow real-time streaming of the logs.

We will add this at some point.

Side note: highly recommending our subreddit [/r/nextdns](https://www.reddit.com/r/nextdns) for feature requests or UI/UX suggestions as more people can jump in to discuss it.
