### ISSUE TITLE
Lists - Switch to/from advanced

### ISSUE THREAD

**Issue by vanj** [nextdns/lists#21]
If I switch on the Lists  > Advanced pill button and make a bunch of selections and then switch it off, my selections are lost. Please fix

**Comment by pe0mot** [comment]
No problem here. Cookies disabled?

**Comment by vanj** [comment]
These are server side settings so I am not sure cookies matter. Olivier@NextDNS confirmed that this is an issue. Here is how to reproduce

1. Go to my.nextdns.io and sign in
2. Go to Lists
3. It defaults to Basic. Select a bunch of pre-configured [bundles ](https://github.com/nextdns/lists/blob/master/bundles.json)e.g. Security, Adware, etc.
4. Switch to Advanced
5. Turn on or off a bunch of lists
6. Switch back to Basic
7. Switch to Advanced - You will see that the selections you made in Step 5 are lost

It is perfectly reasonable that once you enable Advanced mode you are expected to remain in Advanced mode, common in many software configs. From a UI/UX perspective, perhaps a warning can be displayed when switching from Advanced to Basic so user can make a informed decision.

Thanks

**Comment by pe0mot** [comment]
>     7. Switch to Advanced - You will see that the selections you made in Step 5 are lost

Yep, you're right. 

> perhaps a warning can be displayed when switching from Advanced to Basic so user can make a informed decision.
Supported.

**Comment by romaincointepas** [comment]
We will revamp the Lists section soon, and the *simple mode lists* will be mixed with the *advanced mode lists* (while still being recommended first for the less tech-savvy users). There will be no simple/advanced modes anymore.

Side note: highly recommending our subreddit [/r/nextdns](https://www.reddit.com/r/nextdns) for feature requests or UI/UX suggestions as more people can jump in to discuss it.
