### ISSUE TITLE
sort lists

### ISSUE THREAD

**Issue by FernandoMiguel** [nextdns/lists#34]
add sort to lists
* number of entries
* Updated X

**Comment by DaBomby** [comment]
I agree. I assume this would cover the personal blacklist and whitelist as well as the others.

**Comment by romaincointepas** [comment]
We will greatly improve the Lists and Services sections soon with sorts, filters and more signals (like the risk of false positives of a list).

Closing this, our subreddit [/r/nextdns](https://www.reddit.com/r/nextdns) is probably a better place  to discuss feature requests.
