### ISSUE TITLE
Google Pay broken on Android?

### ISSUE THREAD

**Issue by mtverlee** [nextdns/lists#38]
When using the Ads/Trackers lists, Google Pay is broken on Android. Not sure which specific domains, I was unable to find them through my own testing. Just wanted to make you aware.

**Comment by romaincointepas** [comment]
We have released a new version of our Android app that should fix this bug (it doesn't happen to everyone).

If you were using our Android app, can you try again with the latest version? If it still doesn't work, or if you weren't using our Android app, can you talk to us via the chat on our website so we can debug?
