### ISSUE TITLE
Add www.i-dont-care-about-cookies.eu Filter

### ISSUE THREAD

**Issue by Mav3r1x** [nextdns/lists#39]
It would help your EU users a lot not getting bombarded with "accept cookie flyouts" on every single website.

Personally I find `https://www.i-dont-care-about-cookies.eu/` filter list works very well.

**Comment by dimqua** [comment]
Unfortunable, its not possible to implement this functionality on DNS-based level.

**Comment by romaincointepas** [comment]
@dimqua is right, if you check the list itself you will see that most rules are either path rules or css selectors, so while we could add the list, at the end it would really block/hide anything.
