### ISSUE TITLE
Windows spying list

### ISSUE THREAD

**Issue by c-rilaun** [nextdns/lists#52]
Hi everyone !

We all know Windows is far more powerfull tan James Bond, so, it would be nice if we could block Windows spying with NextDNS (telemetry and other stuff).

There is some list available here (IPv4 & IPv6) : [crazy-max/WindowsSpyBlocker](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/doc/data/hosts.md) 

Reach back to me if you need more details, thanks! :-)

**Comment by goodness-from-me** [comment]
Hi! This list is already available. Just enable Advanced mode and you will find it.

**Comment by c-rilaun** [comment]
Indeed, I didn't saw it. My bad I guess !
