### ISSUE TITLE
Add Spanish/Portuguese filter

### ISSUE THREAD

**Issue by josemsanchezb** [nextdns/lists#59]
Add Spanish/Portuguese filters like the [AdGuard Spanish/Portuguese](https://filters.adtidy.org/extension/chromium/filters/9.txt) or the [Fanboy Spanish/Portuguese](https://fanboy.co.nz/fanboy-espanol.txt) .
There’re a lot of Spanish and Portuguese ad & track services that are not blocked by almost all general filters and we need any of these regional filters. Thank you

**Comment by scafroglia93** [comment]
Voila
https://github.com/notracking/hosts-blocklists

**Comment by josemsanchezb** [comment]
OMG! Thank you!!
