### ISSUE TITLE
Support wildcards in lists

### ISSUE THREAD

**Issue by dimqua** [nextdns/lists#6]
Could you please add support for rules like these `||*.example.com^`? They are present in lists supported by [uBlock Origin](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#extended-syntax) and [Adguard](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#special-characters).

It'd be nice to have such feature in bundles as well.

**Comment by romaincointepas** [comment]
I thought `||*.example.com^` was the equivalent of `||example.com^` (which we already support). Do you have an example of a list using `||*.example.com^`?

**Comment by dimqua** [comment]
Your right, bad example. However there are quite useful self-explanatory rules like `||ad*.nexage.com^`, `||adserver.*.yahoodns.net^` and `||w*statistics.info^` in [AdGuard Simplified Domain Names](https://filters.adtidy.org/extension/chromium/filters/15.txt) list, for example.

BTW, does the service support exceptions rules like `@@||guce.advertising.com^`?

**Comment by romaincointepas** [comment]
We don't support `*` inside the domain name at the moment (it's a big hit performance and cost-wise, and we didn't find enough real-world use cases to justify it).

Regarding exceptions, we don't support them yet, but we will soon.

**Comment by dimqua** [comment]
> We don't support * inside the domain name

Is it related to the fact that Unbound doesn't support them?
