### ISSUE TITLE
torrent tracker host to many false positives

### ISSUE THREAD

**Issue by idnovic** [nextdns/lists#7]
www.jamendo.com is wrongly blocked by the torrent list.
Jamendo is a open source music streaming platform.
With free as in libre music.

**Comment by idnovic** [comment]
[ipv4.test-ipv6.csclub.uwaterloo.ca](url) is wrongly blocked

**Comment by romaincointepas** [comment]
For now, best way is to bring up this issue with the list maintainer.

Very soon we will start launching our own list ([like we did for disguised third-party trackers](https://github.com/nextdns/cname-cloaking-blocklist)) for categories like this one that lacks a good list, and we will work our way up to avoid false positives.
